/**
 * Created by magda on 29/06/17.
 */

/*
ta funkcja ma za zadanie:
1) wyszukać i zwrócić część querystring z URI (location.search.substring)
2) z pominięciem znaku ? (począwszy od 1, a nie od 0)
3) podzielenie (split) tego łańcucha na tablicę podstringów po znaku & (w efekcie pozbywamy się tego znaku)
4) przejście pętlą for po tablicy tychże podstringów, które stanowią zestawy: key=value,
5) i podzielenie (split) tychże podstringów po znaku = (w efekcie pozbywamy się tego znaku)
6) przypisanie do zmiennej r tablicy, w której odkodowane komponenty URI będą tworzyły pary key value
7) i ostatecznie zwrócenie tychże wartości zmiennej r
 */
function getRequests() {
    var s1 = location.search.substring(1, location.search.length).split('&'),
        r = {}, s2, i;
    for (i = 0; i < s1.length; i += 1) {
        s2 = s1[i].split('=');
        r[decodeURIComponent(s2[0]).toLowerCase()] = decodeURIComponent(s2[1]);
    }
    return r;
}
// tworzę obiekt slownika
// słownik musi zawierać klucz (id z html) i wartość (treść z html lub jej tłumaczenie)
var myDictionary = {};

//słownik dla jezyka polskiego
myDictionary["pl"] = {
    "stimulus":"Dla mieszkańców i turystów - dowiedz się, co nasze miasto może ci zaoferować!",
    "bigTitle":"Gdańsk pełny wrażeń",
    "monument":"Atrakcje",
    "event":"Wydarzenia",
    "buy":"Kup bilet",
    "add":"Dodaj wydarzenie",
    "contactUs":"Kontakt",
    "attractionsH3":"Atrakcje turystyczne",
    "attractionsH4":"Zabytki, muzea, stałe ekspozycje",
    "attractionsH4add":"Atrakcje turystyczne",
    "attractionsP":"Dowiedz się, co warto zobaczyć i zwiedzić w Gdańsku, obejrzyj galerię najciekawszych miejsc i zaplanuj swój pobyt.",
    "eventsH3":"Wydarzenia",
    "eventsH4":"Kalendarz wydarzeń",
    "eventsH4add":"Wydarzenia",
    "eventsP":"Sprawdź, jakie imprezy planowane są w Gdańsku i zaplanuj przyjazd na wybrane wydarzenia.",
    "buyTicketH3":"Kup bilet",
    "buyTicketH4":"Bilety na wydarzenia",
    "buyTicketH4add":"Kup bilet",
    "buyTicketP":"Skorzystaj z rabatów przedsprzedaży lub last-minute - kup bilety i nie przegap atrakcyjnych imprez.",
    "addEventH3":"Dodaj wydarzenie",
    "addEventH4":"Twoje wydarzenie w sieci",
    "addEventH4add":"Dodaj wydarzenie",
    "addEventP":"Jeśli organizujesz jakieś wydarzenie w Gdańsku, dodaj je do naszego kalendarza, a my je zaprezentujemy.",
    "newsletterH3":"Zapisz się do nas!",
    "newsletterP":"Powiadomimy Cię, gdy nasza strona wystartuje - wystarczy, że podasz swoje imię i email :)",
    "newsletterName":"Imię:",
    "newsletterEmail":"Email:",
    "newsletterInfo":"Podane dane zostaną wykorzystane jedynie na potrzeby portalu wykonanego przez Yellow Group. Zostanie wysłany tylko jeden email informacyjny.",
    "attractionsP1":"W tej sekcji będzie można zapoznać się z atrakcjami turystycznymi w Gdańsku, zarówno tymi historycznymi, sportowymi, jak i tymi przeznaczonymi jedynie dla najmłodzszych odbiorców.",
    "eventsP1":"Nie samymi atrakcjami człowiek żyje. W kategorii wydarzenia pokażemy wszystkie eventy, na których warto być. Warto odwiedzać tę sekcję regularnie.",
    "buyTicketP1":"Nasz portal umożliwia zakup biletów na atrakcje i wydarzenia w Gdańsku.",
    "addEventsP1":"Każdy z użytkowników będzie mógł zaproponować wydarzenie. Również Ty!",
    "showMapH4":"Pokaż na mapie",
    "showMapP1":"Aby pomóc naszym użytkownikom, każda atrakcja będzie zaznaczona na mapie.",
    "shareFriendsH4":"Podziel się ze znajomymi",
    "shareFriendsP1":"Pod artykułami będzie możliwość łatwego dzielenia się nimi z przyjaciółmi za pomocą portali typu social media.",
    "suggestSimilarH4":"Zaproponuj podobne",
    "suggestSimilarP1":"Pod każdą atrakcją zasugerujemy użytkownikowi inne propozycje o bardzo podobnej tematyce.",
    "showWeatherH4":"Pokaż pogodę",
    "showWeatherP1":"Pogoda jest bardzo ważna podczas zwiedzania. Będziesz mógł na bieżąco sprawdzić, czy należy wziąć olejek do opalania czy niestety parasol.",
    "mw1":"Projektantka / kierownik projektów",
    "mw2":"Kocham wszystko, co proste, piękne i funkcjonalne",
    "mw3":"Uwielbiam się uczyć, rozwijać i dążyć do celu",
    "ks1":"Filolożka klasyczna",
    "ks2":"Nałogowa konsumentka estetyki",
    "ks3":"Koneserka przyjemności, niezależnie od ich rozmiarów",
    "jm1":"To mój pierwszy projekt www",
    "jm2":"Z wykształcenia jestem mgr inż. budownictwa",
    "jm3":"W wolnym czasie gram we frisbee, tenis, biegam, a także interesuję się lotnictwem",
};

//słownik dla jezyka angielskiego
myDictionary["en"] = {
    "stimulus":"For locals and tourists alike - learn what our city can offer you!",
    "bigTitle":"Gdansk full of experiences",
    "monument":"Attractions",
    "event":"Events",
    "buy":"Buy a ticket",
    "add":"Add event",
    "contactUs":"Contact",
    "attractionsH3":"Tourist attractions",
    "attractionsH4":"Monuments, museums, permanent expositions",
    "attractionsH4add":"Tourist attractions",
    "attractionsP":"Find out what to see in Gdansk, view the gallery of the most interesting places and plan your stay.",
    "eventsH3":"Events",
    "eventsH4":"Event Calendar",
    "eventsH4add":"Events",
    "eventsP":"Check out what events are planned in Gdansk and plan your arrival at selected events.",
    "buyTicketH3":"Buy a ticket",
    "buyTicketH4":"Event tickets",
    "buyTicketH4add":"Buy a ticket",
    "buyTicketP":"Use pre-sale or last-minute discounts - buy tickets and do not miss attractive events.",
    "addEventH3":"Add event",
    "addEventH4":"Your event on the web",
    "addEventH4add":"Add event",
    "addEventP":"If you organize an event in Gdansk, add it to our calendar and we will present it.",
    "newsletterH3":"Subscribe to us!",
    "newsletterP":"We will notify you when our site starts - just give your name and email :)",
    "newsletterName":"Name:",
    "newsletterEmail":"Email:",
    "newsletterInfo":"The data provided will only be used for the Yellow Group portal. Only one newsletter will be sent.",
    "attractionsP1":"In this section, you will be able to see the tourist attractions of Gdansk, both historical, sports and those intended for children.",
    "eventsP1":"Not the attraction itself, man lives. In the event category, we'll show you all the events you want to participate in. It's worth to visit this section regularly.",
    "buyTicketP1":"Our portal allows you to buy tickets for attractions and events in Gdansk.",
    "addEventsP1":"Each user will be able to propose an event. You too!",
    "showMapH4":"Show on map",
    "showMapP1":"To help our users, each attraction will be marked on the map.",
    "shareFriendsH4":"Share with your friends",
    "shareFriendsP1":"Under the articles will be able to easily share with friends through social media portals.",
    "suggestSimilarH4":"Suggest similar",
    "suggestSimilarP1":"Under each attraction we will suggest you other proposals with a very similar theme.",
    "showWeatherH4":"Show the weather",
    "showWeatherP1":"Weather is very important when exploring. You will be able to see if you should take sunblock oil or unfortunately umbrella.",
    "mw1":"Designer / Project Manager",
    "mw2":"I love everything that is simple, beautiful and functional",
    "mw3":"I love learning, developing and striving for the goal",
    "ks1":"Classical philologist",
    "ks2":"Anemic aesthetics' consumer",
    "ks3":"Connoisseurs of pleasure, regardless of their size",
    "jm1":"This is my first web project",
    "jm2":"I am a graduate of civil engineering",
    "jm3":"In free time I play frisbee, tennis, running, and I am also interested in aviation"
};

//słownik dla jezyka niemieckiego
myDictionary["de"] = {
    "stimulus":"Für Einheimische und Touristen gleichermaßen - lernen, was unsere Stadt, die Sie anbieten können!",
    "bigTitle":"Danzig volle Erfahrung",
    "monument":"Attraktionen",
    "event":"Geschehen",
    "buy":"Kaufen Sie ein Ticket",
    "add":"Event hinzufügen",
    "contactUs":"Kontakt",
    "attractionsH3":"Touristische Attraktionen",
    "attractionsH4":"Denkmäler, Museen, Dauerausstellungen",
    "attractionsH4add":"Touristische Attraktionen",
    "attractionsP":"Erfahren Sie, was in Danzig finden Sie in der Galerie der interessantesten Orte zu sehen und planen Sie Ihren Aufenthalt.",
    "eventsH3":"Geschehen",
    "eventsH4":"Veranstaltungskalender",
    "eventsH4add":"Geschehen",
    "eventsP":"Finden Sie heraus, was Ereignisse in Danzig geplant und planen auf ausgewählte Ereignisse zu gelangen.",
    "buyTicketH3":"Kaufen Sie ein Ticket",
    "buyTicketH4":"Tickets",
    "buyTicketH4add":"Kaufen Sie ein Ticket",
    "buyTicketP":"Nutzen Sie die VVK Rabatte und Last-Minute-Angebote - Karten kaufen und verpassen Sie nicht die attraktiven Veranstaltungen.",
    "addEventH3":"Event hinzufügen",
    "addEventH4":"Ihre Veranstaltung im Netzwerk",
    "addEventH4add":"Event hinzufügen",
    "addEventP":"Wenn Sie eine Veranstaltung in Danzig organisieren, sie zu unserem Kalender hinzufügen und wir werden sie präsentieren.",
    "newsletterH3":"Melden Sie sich an uns!",
    "newsletterP":"Wir werden Sie informieren, wenn wir Seite beginnen - nur, dass Sie Ihren Namen und E-Mail zur Verfügung stellen :)",
    "newsletterName":"Vorname:",
    "newsletterEmail":"Email:",
    "newsletterInfo":"Die angegebenen Daten werden nur für das von der Yellow-Gruppe gemacht Portal verwendet werden. Sie werden nur eine E-Mail-Informationen gesendet werden.",
    "attractionsP1":"In diesem Bereich finden Sie die Sehenswürdigkeiten von Danzig sehen, sowohl die historischen, Sport, und nur die für Kinder bestimmt.",
    "eventsP1":"Kein Mensch lebt die gleichen Attraktionen. In der Kategorie der Ereignisse zeigen alle Veranstaltungen, bei denen es sich lohnt zu beteiligen ist. Es lohnt sich diesen Abschnitt regelmäßig zu besuchen.",
    "buyTicketP1":"Auf unserer Website können Sie Tickets für Attraktionen und Veranstaltungen in Gdansk kaufen.",
    "addEventsP1":"Each user will be able to propose an event. You too!",
    "showMapH4":"Auf der Karte anzeigen",
    "showMapP1":"Um unseren Nutzern zu helfen, wird jede Attraktion auf der Karte angezeigt werden.",
    "shareFriendsH4":"Mit Freunden teilen",
    "shareFriendsP1":"Gemäß der Satzung wird in der Lage sein, leicht sie über Social Media-Portale Typen mit Freunden zu teilen.",
    "suggestSimilarH4":"Vorschlagen ähnlich",
    "suggestSimilarP1":"Unter jeder Attraktion schlagen Sie andere Vorschläge mit sehr ähnlichen Themen.",
    "showWeatherH4":"Wettermeldungen anzeigen",
    "showWeatherP1":"Das Wetter ist sehr wichtig, wenn man auf Tour. Sie werden in der Lage sein zu sehen, ob Sie Sonnencreme oder leider Regenschirm mitnehmen sollten.",
    "mw1":"Der Designer / Projektleiter",
    "mw2":"Ich liebe alles ist einfach, schön und funktional",
    "mw3":"Ich liebe es zu lernen, zu wachsen und das Ziel verfolgen",
    "ks1":"Altphilologe",
    "ks2":"Zwanghafte Verbraucherästhetik",
    "ks3":"Connoisseur des Vergnügens, unabhängig von ihrer Größe",
    "jm1":"Dies ist mein erstes Web-Projekt",
    "jm2":"Ich bin ein Ingenieur MA",
    "jm3":"In meiner Freizeit spiele ich Frisbee, Tennis, Joggen, und interessiert auch in der Luftfahrt"
};

//słownik dla jezyka fińskiego
myDictionary["fi"] = {
    "stimulus":"Paikallisten asukkaiden ja matkailijoiden keskuudessa - oppii mitä kaupunki voi tarjota sinulle!",
    "bigTitle":"Gdansk täysi kokemus",
    "monument":"Nähtävyydet",
    "event":"Tapahtumat",
    "buy":"Osta lippu",
    "add":"Lisää tapahtuma",
    "contactUs":"Kosketus",
    "attractionsH3":"Matkailukohteita",
    "attractionsH4":"Monumentteja, museoita, perusnäyttelyt",
    "attractionsH4add":"Matkailukohteita",
    "attractionsP":"Opi mitä nähdä Gdanskissa, katso galleria mielenkiintoisimmista paikoista ja loman suunnittelusta.",
    "eventsH3":"Tapahtumat",
    "eventsH4":"Tapahtumakalenteri",
    "eventsH4add":"Tapahtumat",
    "eventsP":"Selvitä, mitä tapahtumia suunnitellaan Gdanskissa ja saavut valituista tapahtumista.",
    "buyTicketH3":"Osta lippu",
    "buyTicketH4":"Liput",
    "buyTicketH4add":"Osta lippu",
    "buyTicketP":"Hyödynnä Presale alennukset ja viime hetken tarjoukset - ostaa lippuja ja älä menetä houkuttelevia tapahtumia.",
    "addEventH3":"Lisää tapahtuma",
    "addEventH4":"Tapahtumasi verkossa",
    "addEventH4add":"Lisää tapahtuma",
    "addEventP":"Jos olet järjestämässä tapahtumaa Gdanskissa, lisäämme ne kalenteri ja esitämme niitä.",
    "newsletterH3":"Tilaa meille!",
    "newsletterP":"Ilmoitamme kun alamme sivulle - vain, että annat nimesi ja sähköpostiosoitteesi :)",
    "newsletterName":"Etunimi:",
    "newsletterEmail":"Sähköposti:",
    "newsletterInfo":"Annetut tiedot käytetään vain portaalin tekemät Yellow Group. Sinulle lähetetään vain yhden sähköpostiosoitteen tiedot.",
    "attractionsP1":"Tässä osiossa näet nähtävyyksiä Gdanskin sekä historialliset, urheilu-, ja ne on tarkoitettu vain lapsille.",
    "eventsP1":"Ei ihminen elää samassa nähtävyyksiä. Luokassa tapahtumien näyttää kaikki tapahtumat, joissa on syytä osallistua. Kannattaa käydä tässä osiossa säännöllisesti.",
    "buyTicketP1":"Sivustomme avulla voit ostaa lippuja nähtävyyksiä ja tapahtumia Gdanskissa.",
    "addEventsP1":"Kukin käyttäjä voi ehdottaa tapahtumaan. Myös sinä!",
    "showMapH4":"Näytä kartalla",
    "showMapP1":"Auttaa varmistamiseksi jokainen vetovoima näkyy kartassa.",
    "shareFriendsH4":"Jaa ystävien kanssa",
    "shareFriendsP1":"Alle Artikkelit voi helposti jakaa niitä ystävien kautta sosiaalisen median portaaleja tyyppi.",
    "suggestSimilarH4":"Ehdota samankaltaisia",
    "suggestSimilarP1":"Kuhunkin vetovoima ehdotat muita ehdotuksia hyvin samankaltaisia teemoja.",
    "showWeatherH4":"Näytä sää",
    "showWeatherP1":"Sää on erittäin tärkeää, kun farmari. Voit nähdä, jos sinun pitäisi ottaa aurinkovoide tai valitettavasti sateenvarjo.",
    "mw1":"Suunnittelija / projektipäällikkö",
    "mw2":"Rakastan kaikkea on yksinkertainen, kaunis ja toimiva",
    "mw3":"Rakastan oppia, kasvaa ja tavoitella",
    "ks1":"Klassinen filologi",
    "ks2":"Pakonomainen kuluttaja estetiikka",
    "ks3":"Tuntija ilo, niiden koosta riippumatta",
    "jm1":"Tämä on ensimmäinen web-projektin",
    "jm2":"Olen insinööri MA",
    "jm3":"Vapaa-ajallani pelaan frisbee, tennistä, lenkkeily, ja myös kiinnostunut ilmailun"
};

//słownik dla jezyka francuskiego
myDictionary["fr"] = {
    "stimulus":"Pour les habitants et les touristes - apprendre ce que notre ville peut vous offrir!",
    "bigTitle":"Gdansk expérience complète",
    "monument":"Attractions",
    "event":"événements",
    "buy":"Acheter un billet",
    "add":"Ajouter un événement",
    "contactUs":"Contact",
    "attractionsH3":"Attractions touristiques",
    "attractionsH4":"Les monuments, les musées, les expositions permanentes",
    "attractionsH4add":"Attractions touristiques",
    "attractionsP":"Apprenez ce qu'il faut voir à Gdansk, voir la galerie des endroits les plus intéressants et planifiez votre séjour.",
    "eventsH3":"Evénements",
    "eventsH4":"Calendrier des événements",
    "eventsH4add":"Evénements",
    "eventsP":"Découvrez ce que les événements sont prévus à Gdansk et prévoyez d'arriver sur les événements sélectionnés.",
    "buyTicketH3":"Acheter un billet",
    "buyTicketH4":"Billets",
    "buyTicketH4add":"Acheter un billet",
    "buyTicketP":"Profitez des remises en prévente et offres de dernière minute - acheter des billets et ne manquez pas les événements attrayants.",
    "addEventH3":"Ajouter un événement",
    "addEventH4":"Votre événement dans le réseau",
    "addEventH4add":"Ajouter un événement",
    "addEventP":"Si vous organisez un événement à Gdansk, les ajouter à notre calendrier et nous les présenter.",
    "newsletterH3":"Abonnez-vous à nous!",
    "newsletterP":"Nous vous informerons quand nous commençons à la page - juste que vous fournissez votre nom et votre email :)",
    "newsletterName":"Prénom:",
    "newsletterEmail":"Email:",
    "newsletterInfo":"Les données fournies ne seront utilisées que pour le portail réalisé par le Groupe Jaune. Vous recevrez une seule information par courriel.",
    "attractionsP1":"Dans cette section, vous verrez les sites de Gdansk, les deux historiques, des sports et ceux destinés seulement pour les enfants.",
    "eventsP1":"Aucun homme ne vit les mêmes attractions. Dans la catégorie des événements montrent tous les événements dans lesquels il vaut la peine de participer. Il vaut la peine de visiter cette section régulièrement.",
    "buyTicketP1":"Notre site vous permet d'acheter des billets pour les attractions et les événements de Gdansk.",
    "addEventsP1":"Chaque utilisateur sera en mesure de proposer un événement. Vous aussi!",
    "showMapH4":"Voir sur la carte",
    "showMapP1":"Pour aider nos utilisateurs, chaque attraction seront affichés sur la carte.",
    "shareFriendsH4":"Partager avec des amis",
    "shareFriendsP1":"En vertu des articles seront en mesure de les partager facilement avec des amis via le type de portails de médias sociaux.",
    "suggestSimilarH4":"Proposer similaire",
    "suggestSimilarP1":"Sous chaque attraction vous suggérer d'autres propositions avec des thèmes très similaires.",
    "showWeatherH4":"Afficher la météo",
    "showWeatherP1":"Le temps est très important lors de tournées. Vous pourrez voir si vous devez prendre la crème solaire ou parapluie, malheureusement.",
    "mw1":"Le concepteur / chef de projet",
    "mw2":"J'aime tout est simple, beau et fonctionnel",
    "mw3":"J'aime apprendre, de grandir et de poursuivre l'objectif",
    "ks1":"Philologue classique",
    "ks2":"Compulsive une esthétique à la consommation",
    "ks3":"Connaisseur de plaisir, quelle que soit leur taille",
    "jm1":"Ceci est mon premier projet web",
    "jm2":"Je suis ingénieur MA",
    "jm3":"Dans mon temps libre je joue au frisbee, le tennis, le jogging, et également intéressé par l'aviation"
};

//słownik dla jezyka hiszpańskiego
myDictionary["es"] = {
    "stimulus":"Para locales y turistas por igual - aprender lo que nuestra ciudad puede ofrecerle!",
    "bigTitle":"Gdansk experiencia completa",
    "monument":"Atracciones",
    "event":"Eventos",
    "buy":"Comprar un billete",
    "add":"Añadir evento",
    "contactUs":"Contacto",
    "attractionsH3":"Atracciones turísticas",
    "attractionsH4":"Monumentos, museos, exposiciones permanentes",
    "attractionsH4add":"Atracciones turísticas",
    "attractionsP":"Aprender qué ver en Gdansk, ver la galería de los lugares más interesantes y planificar su estancia.",
    "eventsH3":"Eventos",
    "eventsH4":"Calendario de eventos",
    "eventsH4add":"Eventos",
    "eventsP":"Averigüe lo que se planifican eventos en Gdansk y va a llegar en eventos seleccionados.",
    "buyTicketH3":"Comprar un billete",
    "buyTicketH4":"Entradas",
    "buyTicketH4add":"Comprar un billete",
    "buyTicketP":"Aprovechar los descuentos de pre-venta y ofertas de última hora - comprar los billetes y no se pierda los eventos atractivos.",
    "addEventH3":"Añadir evento",
    "addEventH4":"Su evento en la red",
    "addEventH4add":"Añadir evento",
    "addEventP":"Si está organizando un evento en Gdansk, agregarlos a nuestro calendario y vamos a presentarlos.",
    "newsletterH3":"Suscribirse a nosotros!",
    "newsletterP":"Te avisaremos cuando comenzamos la página - sólo que proporcione su nombre y correo electrónico :)",
    "newsletterName":"Nombre:",
    "newsletterEmail":"Email:",
    "newsletterInfo":"Los datos proporcionados serán utilizados únicamente para el portal realizado por el Grupo Amarillo. Se le mandará un único e-mail.",
    "attractionsP1":"En esta sección, podrás ver los puntos de interés de Gdansk, tanto los históricos, los deportes y los diseñados para los niños.",
    "eventsP1":"Ningún hombre vive las mismas atracciones. En la categoría de eventos mostrar todos los eventos en los que vale la pena participar. Vale la pena visitar esta sección regularmente.",
    "buyTicketP1":"Nuestro sitio web le permite comprar entradas para atracciones y eventos en Gdansk.",
    "addEventsP1":"Cada usuario podrá proponer un evento. También usted!",
    "showMapH4":"Mostrar en el mapa",
    "showMapP1":"Para ayudar a nuestros usuarios, cada atracción se mostrará en el mapa.",
    "shareFriendsH4":"Compartir con amigos",
    "shareFriendsP1":"En virtud de los artículos será capaz de compartir fácilmente con amigos a través de los medios de comunicación social, tipo de portales.",
    "suggestSimilarH4":"Sugerir similares",
    "suggestSimilarP1":"Bajo cada atracción que sugieren otras propuestas con temas muy similares.",
    "showWeatherH4":"Mostrar el tiempo",
    "showWeatherP1":"El tiempo es muy importante cuando se gira. Usted será capaz de ver si debe tomar crema solar o por desgracia paraguas.",
    "mw1":"El gerente diseñador / proyecto",
    "mw2":"Me encanta todo es simple, hermoso y funcional",
    "mw3":"Me encanta aprender, crecer y lograr el objetivo",
    "ks1":"Filólogo clásico",
    "ks2":"Compulsiva una estética de consumo",
    "ks3":"Conocedor de placer, independientemente de su tamaño",
    "jm1":"Este es mi primer proyecto web",
    "jm2":"Soy ingeniero MA",
    "jm3":"En mi tiempo libre yo juego disco volador, tenis, jogging, y también interesado en la aviación"
};

// definiuję zmienną, do której przypisuję obiekt, zawierający wszystkie zminene z URI takie jak lang : "en"
var QueryString = getRequests();
// interesuje mnie tylko zmienna lang z URI więc definiuję taką zmienną, która trzymać będie tylko lang
var global_lang = QueryString['lang'];

// jak strona ładuje się po raz pierwszy, to nie wyślewieta się tłumaczenie, lecz pokazują się oryginalne teksty z html'a
if (global_lang !== null) {
    // pętlą for przechodzimy po wszystkich kluczach z danego słownika
    for (key in myDictionary[global_lang]) {
        console.log(key);
        // podmieniamy HTML dla nadych kluczy i zastępujemy oryginał tłumaczeniem
        document.getElementById(key).innerHTML = myDictionary[global_lang][key];
    }
}